from setuptools import setup, find_packages

setup(
    name="visioncapt",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "transformers>=4.28.0",
        "pillow>=9.0.0",
        "numpy>=1.24.0",
        "matplotlib>=3.7.0",
        "tqdm>=4.65.0",
        "pyyaml>=6.0",
        "omegaconf>=2.3.0",
        "wandb>=0.15.0",
        "tensorboard>=2.12.0",
        "gradio>=3.32.0",
        "ftfy>=6.1.1",
        "regex>=2022.10.31",
        "pycocotools>=2.0.6",
        "accelerate>=0.19.0",
        "deepspeed>=0.9.0",
        "nltk>=3.8",
        "rouge>=1.0.1",
        "bitsandbytes>=0.39.0",
        "peft>=0.4.0",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="A vision-language model for image captioning using small LLMs",
    keywords="vision, language, captioning, deep-learning, small-llm",
    url="https://github.com/yourusername/vlm-caption",
)